export default {
    "data":[
        {
            "regionCode":130000,
            "province":"河北省"
        },
        {
            "regionCode":140000,
            "province":"山西省"
        },
        {
            "regionCode":150000,
            "province":"内蒙古自治区"
        },
        {
            "regionCode":210000,
            "province":"辽宁省"
        },
        {
            "regionCode":220000,
            "province":"吉林省"
        },
        {
            "regionCode":230000,
            "province":"黑龙江省"
        },
        {
            "regionCode":320000,
            "province":"江苏省"
        },
        {
            "regionCode":330000,
            "province":"浙江省"
        },
        {
            "regionCode":340000,
            "province":"安徽省"
        },
        {
            "regionCode":350000,
            "province":"福建省"
        },
        {
            "regionCode":360000,
            "province":"江西省"
        },
        {
            "regionCode":370000,
            "province":"山东省"
        },
        {
            "regionCode":410000,
            "province":"河南省"
        },
        {
            "regionCode":420000,
            "province":"湖北省"
        },
        {
            "regionCode":430000,
            "province":"湖南省"
        },
        {
            "regionCode":440000,
            "province":"广东省"
        },
        {
            "regionCode":450000,
            "province":"广西壮族自治区"
        },
        {
            "regionCode":460000,
            "province":"海南省"
        },
        {
            "regionCode":510000,
            "province":"四川省"
        },
        {
            "regionCode":520000,
            "province":"贵州省"
        },
        {
            "regionCode":530000,
            "province":"云南省"
        },
        {
            "regionCode":540000,
            "province":"西藏自治区"
        },
        {
            "regionCode":610000,
            "province":"陕西省"
        },
        {
            "regionCode":620000,
            "province":"甘肃省"
        },
        {
            "regionCode":630000,
            "province":"青海省"
        },
        {
            "regionCode":640000,
            "province":"宁夏回族自治区"
        },
        {
            "regionCode":650000,
            "province":"新疆维吾尔自治区"
        }
    ]
}